name: NightlyTestJob
#on: [push]
on:
  schedule:
    - cron:  '30 1 * * *'
jobs:
  Test-GitHUb-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install python modules
        run: pip install nbconvert jupyter yfinance pandas-datareader matplotlib nltk
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/colab_notebooks
      - name: Run notebooks
        run: jupyter nbconvert --to notebook --execute ${{ github.workspace }}/yt_videos_colabs/PythonInvest_com_2_2_EveryDay_Sentiment_Analysis_of_Financial_News_.ipynb
      - name: Push news
        run: | 
          git config user.name github-actions
          git config user.email github-actions@github.com
          find . -name "*TSLA_news_sentiments_*.csv" -exec git add {} \; && git commit -m "update news sentiment"
          git push
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: echo "🍏 This job's status is ${{ job.status }}."
